### ISSUE TITLE
[Send Confirmation modal] Unreadable white text color 

### ISSUE THREAD

**Issue by wrt-github** [mobilecoinofficial/desktop-wallet#108]
### Machine

MobileCoin-Desktop-Wallet-beta-v030
macOS Big Sur 11.2.3
Display: 15.4-inch (2880 × 1800)

### Description

This screenshot depicts the Send Confirmation modal:

<img width="812" alt="send-button-scroll-cut-off" src="https://user-images.githubusercontent.com/82286902/114283100-eb18a000-99fc-11eb-9f9c-d9eb038edf97.png">

The areas highlighted by red rectangles contain text labels that should be visible. However, the font color for those text labels appears to be white. Because of their color, they blend into the background. That makes them impossible to read.

### Reproducing the bug

Click the **Send/Receive** tab at the top of the app. Type text into the **Recipient's Public Address** and the **MOB Amount**. Click **Send Payment**. 

You will be presented with a modal confirmation. You won't be able to read the text labels in the center of the modal.

**Comment by wrt-github** [comment]
Found some discussion on the MobileCoin Official Signal Group:

The group member named, 🌊, writes:

> Just some UI feedback for MacOS (will install on Linux later this afternoon): When "Light Mode" is selected, some of the text is washed out prior to confirming a transaction as you can see in the attached images. The first image with "Light Mode" selected and the second image is "Dark Mode". In the previous version of the MacOS desktop wallet (v0.1.3), desktop appearance selection didn't seem to apply to the wallet (third image is previous desktop wallet with "light mode" selected). Also, blue font might not be the ideal choice in future iterations. Obviously these things are minor, but I figure you might appreciate the feedback mainly @Sara Drakeley Hall . As far as functionality, everything seems great. One minor bug with the new tx history feature, but I need to investigate further and I know you guys are still working on it. Thanks again for all your effort on this project!

![Limitation of Liability  Release, and Indemnity](https://user-images.githubusercontent.com/82286902/114288304-5f663a00-9a23-11eb-9953-45de50f8ce1c.jpeg)

![SETTINGS](https://user-images.githubusercontent.com/82286902/114288306-60976700-9a23-11eb-8fcc-8faa27b8aea2.jpeg)

![Send MOB Confirmation](https://user-images.githubusercontent.com/82286902/114288308-612ffd80-9a23-11eb-8d74-730bbedf8c25.jpeg)

![Amount](https://user-images.githubusercontent.com/82286902/114288309-61c89400-9a23-11eb-8cd2-8bdb9ce0dd92.jpeg)

**Comment by johnedma** [comment]
@wrt-github thanks for opening this issue and for the feedback as well, the fix has been merged into main! https://github.com/mobilecoinofficial/desktop-wallet/pull/109 👍🏽
