### ISSUE TITLE
yarn install

### ISSUE THREAD

**Issue by pavoltravnik** [mobilecoinofficial/desktop-wallet#111]
Unable to install this on Mac
MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
2.4 GHz Quad-Core Intel Core i5
16 GB 2133 MHz LPDDR3

git clone ...
yarn install

[desktop-wallet.log](https://github.com/mobilecoinofficial/desktop-wallet/files/6302394/desktop-wallet.log)

**Comment by johnedma** [comment]
hey @pavoltravnik, we're aware of the issue and have a work around but looking for an across the board solution - will get back with you soon on the fix!
