### ISSUE TITLE
404 on all linux downloads for v0.4.0

### ISSUE THREAD

**Issue by PietroProraso** [mobilecoinofficial/desktop-wallet#156]
I can only download MacOS versions but none of the Linux versions here:

https://github.com/mobilecoinofficial/desktop-wallet/releases/tag/v0.4.0

**Comment by sugargoat** [comment]
Apologies! I am in the process of building the linux packages with the latest version of full-service, which had a fix for database migration. I should have these up hopefully by EOD

**Comment by sugargoat** [comment]
Hi @PietroProraso, 

The [release has been updated with the linux packages](https://github.com/mobilecoinofficial/desktop-wallet/releases/tag/v0.4.0). Please let us know if you run into any more issues!
