### ISSUE TITLE
Access Denied javascript error

### ISSUE THREAD

**Issue by kareldonk** [mobilecoinofficial/desktop-wallet#163]
Installed release version `mobilecoin-desktop-wallet-beta-v040_0.4.0_amd64.deb` on Ubuntu and when starting the app I got the following javascript error:

![image](https://user-images.githubusercontent.com/12107205/125861108-0e5f302b-71c9-40c0-bdef-05c2381d5c62.png)

I had to manually give the script `start-full-service.sh` in folder `/opt/MobileCoin-Desktop-Wallet-beta-v040/full-service-bin` execute permission with `chmod +x start-full-service.sh`.
Might want to add this to your installer.

**Comment by BrianCorbin** [comment]
This should be resolved with the new release! :)
