### ISSUE TITLE
passphrase

### ISSUE THREAD

**Issue by two-x** [mobilecoinofficial/desktop-wallet#165]
How do I figure out my passphrase for my wallet?  I never had the option to set it, yet when I open the wallet I see

<img width="448" alt="mobilecoin" src="https://user-images.githubusercontent.com/41216347/128455462-89be5576-0e90-499b-b67e-8b113c4d8e29.png">

**Comment by edsimpsons83** [comment]
Getting this issue as well with the new v1.1.0.

**Comment by BrianCorbin** [comment]
With the new v1.1.0, this should be alleviated. Could you elaborate, @edsimpsons83 on what is happening? Is the unlock wallet screen popping up immediately, or does it say Create Wallet?
