### ISSUE TITLE
Maintain the same package name on Debian/Ubuntu

### ISSUE THREAD

**Issue by PeriferiaGalactica** [mobilecoinofficial/desktop-wallet#175]
With each release, the desktop wallet has been receiving a new package name on Debian/Ubuntu, which results in multiple installed instances of 'MobileCoin Wallet'.

(Recently I ended up with four installed instances of the wallet.)

For instance, I already have the package `mobilecoin-wallet-v1.1.0` installed, but in trying to update to v1.1.1, apt wants to install the *new* package `mobilecoin-wallet-v1.1.1`.

This would ostensibly be avoided by maintaining the same package name.

Instead, I have to remove the old one first, because further, as a new and different package it tries to install atop the existing resources in `/opt/MobileCoin Wallet/`, which leads to apt errors upon installation as it attempts to overwrite files such as `resources/resources/icon.ico`

**Comment by PeriferiaGalactica** [comment]
> What is the preferred method of updating on Ubuntu? The v1.1.0 release notes say “Auto update added for installing new releases”. Should it be auto updating?

Unless installing the .deb (`apt install ./package.deb`) also adds MobileCoin's package repository to `/etc/apt/sources.list.d/`, then I do not expect any auto-updating of that package by way of `apt update && apt upgrade` or otherwise.

Instead, I expect to always download the latest .deb and install as above, which as is, results in multiple versions of MobileCoin.

If you're distributing a .AppImage, then I generally expect auto-updating whenever I run the AppImage.

In either case, this may just be solved by refraining from renaming it in `package.json` with every release:

https://github.com/mobilecoinofficial/desktop-wallet/blame/ba5191568d9b500d64b4847f4f0990a116c4ed7f/package.json#L2

**Comment by BrianCorbin** [comment]
Ah, okay thank you for the info! I will chat with the team about that and try to standardize the name of the package and prevent from changing it version to version. Will keep you updated in this thread when we have a solution implemented!

**Comment by BrianCorbin** [comment]
This should now be consistent :)
