### ISSUE TITLE
Import account not available upon installation of 1.1.1

### ISSUE THREAD

**Issue by kareldonk** [mobilecoinofficial/desktop-wallet#176]
After installing a fresh copy of the wallet version 1.1.1 on the first screen you immediately are presented with the option to create an account, but the option to "import account instead" does not appear until after you first set a password on the first create an account screen, and move to the next screen to set an accountname. 
![image](https://user-images.githubusercontent.com/12107205/129913445-fa64a8bf-9518-42a2-a5bb-40415a0f9084.png)
![image](https://user-images.githubusercontent.com/12107205/129910650-2879e314-a33c-4b5d-b90a-b9478271990f.png)
It's a bit confusing in 1.1.1. The way it was in 0.4.0 made more sense, where you had the "import account" button immediately on the first screen upon launching the wallet after installation.

**Comment by PeriferiaGalactica** [comment]
This behaviour was also in v1.1.0, and initially confused me as well. Agreed with moving the password creation screen deeper, and Create/Import being primary.

**Comment by BrianCorbin** [comment]
So, a "Wallet" and an "Account" are 2 different things. First, a wallet must be created, which is managed by an instance of full-service and information is stored in a SQL database locally. This database must be encrypted with a passphrase. Only once this is created can you then create or import an account _into_ said wallet. The reason for this change is in part because multiple accounts are now supported, among other reasons.

**Comment by kareldonk** [comment]
Yes I understand, but it's a bit confusing. When you get presented with the Create Wallet screen, it appears that the only option you have is that you have to create a completely new wallet which will have its own and new address. 
For existing users this is not what they would want as they would want to use their previous/existing address. 
Perhaps a text below that screen explaining that you will be able to import your previous account(s)/address(es) later into the new wallet would prevent this confusion.
But even better would be to just put the import account button on the first screen, and when people click that, ask to set a new password before importing the account.
Perhaps this confusion is also because I was used to the previous interface, but I'm not sure.
