### ISSUE TITLE
Version 1.1.1 does not work on PureOS

### ISSUE THREAD

**Issue by kareldonk** [mobilecoinofficial/desktop-wallet#177]
I installed and used 0.4.0 without issue on PureOS (debian based). But 1.1.1 does not launch after installation when clicking the icon. I haven't had time yet to do more in dept troubleshooting but I thought I'd let you know.

**Comment by BrianCorbin** [comment]
Is this still an issue? If so, please reopen

**Comment by kareldonk** [comment]
Still an issue with the latest 1.5.0 version. This is what I get in a terminal on PureOS:

```
kareld@karel-pc:/opt/MobileCoin Wallet$ ./mobilecoin-wallet
LaunchProcess: failed to execvp:
/opt/MobileCoin
Trace/breakpoint trap
kareld@karel-pc:/opt/MobileCoin Wallet$ [4357:0100/000000.885749:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
```

It then just stays there and does nothing.

In contrast when I run the older beta v040 version I get this and the application starts normally:

```
kareld@karel-pc:/opt/MobileCoin-Desktop-Wallet-beta-v040$ ./mobilecoin-desktop-wallet-beta-v040
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AUTOUPDATER ENABLED
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
APPIMAGE env is not defined, current application is not an AppImage
Looking for Full Service binary in /opt/MobileCoin-Desktop-Wallet-beta-v040/full-service-bin
ledgerFullServiceDbPath /home/kareld/.config/MobileCoin-Desktop-Wallet-beta-v040/full-service/ledger-db
fullServiceDbPath /home/kareld/.config/MobileCoin-Desktop-Wallet-beta-v040/full-service/wallet-db
>>>>>>>>>>>>> INFO     2022-01-29T11:10:19.041Z INITIALIZING LOGGER
08:13:58.579 › APPIMAGE env is not defined, current application is not an AppImage
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
libva error: va_getDriverName() failed with unknown libva error,driver_name=(null)
```

**Comment by kareldonk** [comment]
Ok I found the problem: a space in the installation folder `"/opt/MobileCoin Wallet"`.
When I rename that folder to `"/opt/MobileCoin-Wallet"` it works.

Foldernames and filenames with spaces should be placed in quotes. Probably this is not done in your code when you try to launch a process.

For some reason this is not an issue on Ubuntu.

In version v040 you guys placed dashes instead of spaces in the foldername.

**Comment by david1alvarez** [comment]
Thank you for bringing this to our attention! We have created a ticket and will bring it into our development process. If this is a hard-blocking issue, please let us know.
