### ISSUE TITLE
Checksums for releases

### ISSUE THREAD

**Issue by suddenlyfleck** [mobilecoinofficial/desktop-wallet#190]
Releases like 

https://github.com/mobilecoinofficial/desktop-wallet/releases/tag/v1.3.0

come with a file `latest-linux.yml` that seems to contain a sha512 hash for the AppImage release.

Confusing, from my perspective, is:
The checksum It is shorter than what the sha512sum binary produces.
The checksum contains special characters (`+` an `\` for example).

Be that as it may.

I wondered, whether the AppImage will check itself against the checksum in its corresponding latest-linux.yml file (in whatever way this checksum is produced).
To check this, I attached a few empty bytes to the end of the file (`truncate -s +3 MobileCoin-Wallet-1.3.0.AppImage`) but wasn't greeted with any waring when starting the appimage.

How can I check the validity of the file? (how was the checksum produced?)

**Comment by suddenlyfleck** [comment]
So, this really bugged me. 

Here's a small python function to get the sha512 checksum in the same format as written in `latest-linux.yml`:

```python
import base64
import hashlib

def sha512sum_base64(filePath):
    myHash  = hashlib.sha512()
    byteArray  = bytearray(128*1024)
    memView = memoryview(byteArray)
    with open(filePath, 'rb', buffering=0) as f:
        for n in iter(lambda : f.readinto(memView), 0):
            myHash.update(memView[:n])
    base64Hash = base64.b64encode(myHash.digest())
    return base64Hash
```
Calling `sha512sum_base64(/path/to/MobileCoin-Wallet-1.4.0.AppImage)` results in `b'iSB+eWEbpbxU+QDUF9hQXDn9ErJdZ2U4NtnD7W06sk2+Rz8Vh/6Xfc/SjalvB5B7o/tpA5QUz5IX3rA9wkHh1w=='`, i.e. similar to the contents of `latest-linux.yml`.

The weird base64 format of the hash value is apparently a default of "electron builder".

**Comment by david1alvarez** [comment]
checksums can be generated via the command `openssl dgst -sha512 -binary MobileCoin-Wallet-1.4.0.AppImage | openssl enc -base64`
