### ISSUE TITLE
Send transaction screen left in bad state after successful send to a contact

### ISSUE THREAD

**Issue by holtzman** [mobilecoinofficial/desktop-wallet#277]
After sending to a contact, the send screen has various fields zeroed to ready it for a new send.

However, it zeros the Recipient public address without zeroing the contact pulldown to the default "Contact from list (optional)".  This leaves the user unable to send to the same contact again without flipping the contact to another and then back again.

Either the contact pull-down should be reset to the default, or the address should not be zeroed.

I recommend resetting the contact pull-down along with zeroing the address, returning the input form to its default state across the board, ready for another send.

Below is a screen cap of the bad state.

![image](https://user-images.githubusercontent.com/768487/199795988-078bc0cc-1d18-4cd2-a0ff-da5aec228f60.png)

**Comment by Shramp** [comment]
this will be fixed by https://github.com/mobilecoinofficial/desktop-wallet/pull/276/commits/a1aa8240cf11a290a186431b71294656825a9c0f in 1.7
