### ISSUE TITLE
ERR_CONNECTION_REFUSED trying to contact localhost:9090 

### ISSUE THREAD

**Issue by PeteySteves3** [mobilecoinofficial/desktop-wallet#290]
Hi,

I'm seeing ERR_CONNECTION_REFUSED as I try to log in to the desktop wallet. In the developer tools, I see this:

![image](https://user-images.githubusercontent.com/120437372/207377726-7d5a2ac2-27f7-4eba-9031-0cfd0e20e676.png)

There area  variety of logs and no documentation about the logs, so I'm not sure what you'd like or what I could capture.

- PureOS (Debian flavor)
- Seeing this with 1.7.0 and 1.6.4
- Seeing this on .deb and AppImage (thank you for building AppImage btw)
- Welcome screen --> input password --> it just shows the "I'm doing something" wheel until it hits (presumably) its connection attempts limit, and fails silently.

Perhaps the daemon at localhost:9090 isn't starting, or is inaccessible for some other reason?

**Comment by eranrund** [comment]
Hello @PeteySteves3,

Can you please download the `.tar.gz` file, and then try running `./mobilecoin-wallet-1.7.0/full-service-bin/full-service`? I wonder what you would see when you do that.

Thanks.

**Comment by PeteySteves3** [comment]
I assume you mean `./mobilecoin-wallet-1.7.0/full-service-bin/mainnet/full-service`

I see: 

`adsfadsf@something:~$ '/mobilecoin-wallet-1.7.0/full-service-bin/mainnet/full-service' 
error: The following required arguments were not provided:
  --ledger-db <LEDGER_DB>
  --peer <PEERS>
  --tx-source-url <TX_SOURCE_URLS>

Usage: full-service --ledger-db <LEDGER_DB> --peer <PEERS> --tx-source-url <TX_SOURCE_URLS>

For more information try '--help'
`

Obviously it requires some params, I pointed it to the ledger-db (easy to find), but I don't know where the others are.

**Comment by eranrund** [comment]
Interesting. That means it is able to start, so I am wondering why you are getting the connection refused error.
Is there anything in a log file that matches the pattern `/tmp/full-service-*`?

**Comment by PeteySteves3** [comment]
`grep -rnw  '/home/asdfasdf/.config/MobileCoin Wallet'    -e '*/tmp/full-service-*'` 

and

`grep -rnw  '/home/asdfasdf/Downloads/mobilecoin-wallet-1.7.0'    -e '*/tmp/full-service-*'` 

Don't return anything of interest, I don't think. A few hits in the start scripts for the daemon, the parts that presumably write the things you're interested in to log files. If there's a specific file you'd like to inspect lmk.

**Comment by eranrund** [comment]
Do the log files exist at all? If so, can you paste the first 20 lines or so?

**Comment by PeteySteves3** [comment]
Can you point specifically to which file you're interested in? Where would it be? What would it be named?

**Comment by eranrund** [comment]
Its name would start with /tmp/full-service-
The full name [contains a timestamp](https://github.com/mobilecoinofficial/desktop-wallet/blob/main/full-service-bin/mainnet/start-full-service.sh#L34) so there is no way for me to know it.

**Comment by PeteySteves3** [comment]
No files that start with `full-service-` in `/tmp`.

Just to be 100% clear, you're not talking about a subfolder of either `.config/MobileCoin Wallet` or `mobilecoin-wallet-1.7.0` that is named `tmp`, but rather the tmp folder in the root of the filesystem, right?

**Comment by eranrund** [comment]
Yes, correct. Which version of PureOS are you using?
I will try installing it on a virtual machine and see if I can find out whats going on.

**Comment by PeteySteves3** [comment]
lsb_release -a reports PureOS Byzantium 10.0

Thank you for looking in to this

**Comment by eranrund** [comment]
I just tried it on a stock PureOS10, and it ran fine so unfortunately I am not sure what is wrong with your system. I used the AppImage file.

![image](https://user-images.githubusercontent.com/1485066/207743018-4fcbd5ce-f6a6-43f5-a2be-05f163a26302.png)

**Comment by eranrund** [comment]
I checked the dev tools when I start the wallet and it does show a few connection refused lines, so I think that is fine. It takes the backend a few seconds to start accepting connections.

**Comment by PeteySteves3** [comment]
I really appreciate you looking in to it!

**Comment by eranrund** [comment]
No problem! Unless there is any additional information, is it okay if I close this issue?

**Comment by PeteySteves3** [comment]
Please go ahead and close it.
