### ISSUE TITLE
Im having an issue getting full service running, is this good to use? What boot-up commands do i need for ubuntu and prod

### ISSUE THREAD

**Issue by jayzalowitz** [mobilecoinofficial/desktop-wallet#96]
https://gist.github.com/jayzalowitz/fd7c8b76c3dce401f33a7fb2527b118b

**Comment by vmavromatis** [comment]
I'm far far far from being a knowledgeable user but I suspect that you are using conflicting settings - PROD enclave (production.json) and TEST nodes URLs at the same time. Also, maybe this project would be a better place to post this Q https://github.com/mobilecoinofficial/full-service

**Comment by jayzalowitz** [comment]
@vmavromatis is there a list of things I need to run to do production here

**Comment by vmavromatis** [comment]
Scratch my previous answer - seems you have the right namespace for the testnet enclave - I assume that's what you want to deploy (https://enclave-distribution.prod.mobilecoin.com/production.json is the production one). So no clue what's wrong here sorry :(

**Comment by BrianCorbin** [comment]
Closing as this should be resolved with new version(s) of desktop wallet.
